apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-03-12T19:08:45Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: InfluxDB
  name: monitoring-influxdb
  namespace: kube-system
  resourceVersion: "1709"
spec:
  clusterIP: 10.100.157.27
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    k8s-app: influxGrafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
