#cloud-config
#
# install via coreos-install -d /dev/sda -C stable -c cloud-config.yaml
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzjpDwk2BwYtYfa8EQdmtZAMmpl23zEr8jaioG5CD+rwGSyoQPpszw+yC0Bo5TjDbesYlWDw1d/nVRIJf+i/HAPAs5Qq43iyd1gbSzYuDr3Tgi8T/zMcjwAlyAOszftNOyIbaCyhoYW02f/ih7cZVjDORWJq8EzTNXI7Cot6Q34P+xCYcM+sxmtWOxxRSMx5GfClbawXDz+p5rmvUxuvcTRCLYRM9ZA73tiJWXbbVaXX4EPxNA0L6GryrEr7qmTz6XGcZaiL+GlcIdfRoAO8YOSRF4rocw17b3D0Zkd/Av0f+55BOmbmUFzLD9aFMDWx+mDgsOIs2BHGicX5imOHzWw== tobias.schwab@dynport.de
coreos:
  update:
    reboot-strategy: off
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.1.0.0/16", "Backend": {"Type": "vxlan"}}'
